package view;

import controller.ControllerCurtir;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author mcruz
 */
public class CurtidasFrame extends javax.swing.JFrame {

    private ControllerCurtir c;
    
    public CurtidasFrame() {
    initComponents(); 
    c = new ControllerCurtir(this);
    c.carregarArtistasCurtidos();

}
    


    public CurtidasFrame(JLabel artistascurtidos, JButton bt_descurtir, JLabel lbl_resultado_curtidas, JTextField txt_descurtir_artista) {
        this.artistascurtidos = artistascurtidos;
        this.bt_descurtir = bt_descurtir;
        this.lbl_resultado_curtidas = lbl_resultado_curtidas;
        this.txt_descurtir_artista = txt_descurtir_artista;
    }

    public JLabel getArtistascurtidos() {
        return artistascurtidos;
    }

    public void setArtistascurtidos(JLabel artistascurtidos) {
        this.artistascurtidos = artistascurtidos;
    }

    public JButton getBt_descurtir() {
        return bt_descurtir;
    }

    public void setBt_descurtir(JButton bt_descurtir) {
        this.bt_descurtir = bt_descurtir;
    }

    public JLabel getLbl_resultado_curtidas() {
        return lbl_resultado_curtidas;
    }

    public void setLbl_resultado_curtidas(JLabel lbl_resultado_curtidas) {
        this.lbl_resultado_curtidas = lbl_resultado_curtidas;
    }

    public JTextField getTxt_descurtir_artista() {
        return txt_descurtir_artista;
    }

    public void setTxt_descurtir_artista(JTextField txt_descurtir_artista) {
        this.txt_descurtir_artista = txt_descurtir_artista;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbl_resultado_curtidas = new javax.swing.JLabel();
        bt_descurtir = new javax.swing.JButton();
        artistascurtidos = new javax.swing.JLabel();
        txt_descurtir_artista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_resultado_curtidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_resultado_curtidas.setText("''");

        bt_descurtir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_descurtir.setText("Descurtir");
        bt_descurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtirActionPerformed(evt);
            }
        });

        artistascurtidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        artistascurtidos.setText("Artistas Curtidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(artistascurtidos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_descurtir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_descurtir, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_resultado_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(artistascurtidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_resultado_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_descurtir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_descurtir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bt_descurtirActionPerformed(java.awt.event.ActionEvent evt) {                                             
        c.excluirCurtidas();
    }                                            

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Curtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Curtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Curtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Curtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Curtidas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel artistascurtidos;
    private javax.swing.JButton bt_descurtir;
    private javax.swing.JLabel lbl_resultado_curtidas;
    private javax.swing.JTextField txt_descurtir_artista;
    // End of variables declaration                   
}
