package view;

import controller.ControllerHistorico;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class HistoricoFrame extends javax.swing.JFrame {
    private ControllerHistorico c;
 
 
    public HistoricoFrame() {
        initComponents();
        c = new ControllerHistorico(this);
    }

    public HistoricoFrame(JLabel UltimosArtis, JButton btnCarregarHistorico, JLabel lblHistorico) {
        this.UltimosArtis = UltimosArtis;
        this.btnCarregarHistorico = btnCarregarHistorico;
        this.lblHistorico = lblHistorico;
    }

    public JLabel getUltimosArtis() {
        return UltimosArtis;
    }

    public void setUltimosArtis(JLabel UltimosArtis) {
        this.UltimosArtis = UltimosArtis;
    }

    public JButton getBtnCarregarHistorico() {
        return btnCarregarHistorico;
    }

    public void setBtnCarregarHistorico(JButton btnCarregarHistorico) {
        this.btnCarregarHistorico = btnCarregarHistorico;
    }

    public JLabel getLblHistorico() {
        return lblHistorico;
    }

    public void setLblHistorico(JLabel lblHistorico) {
        this.lblHistorico = lblHistorico;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        UltimosArtis = new javax.swing.JLabel();
        lblHistorico = new javax.swing.JLabel();
        btnCarregarHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UltimosArtis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UltimosArtis.setText("Últimos Artistas");

        lblHistorico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHistorico.setText("''");

        btnCarregarHistorico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarregarHistorico.setText("Atualizar");
        btnCarregarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarregarHistorico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UltimosArtis, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(UltimosArtis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(btnCarregarHistorico)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>                        

    private void btnCarregarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        c.carregarUltimosHistoricos();
    }                                                    

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HistóricoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HistóricoFrame.class.getName()).log(java.util.logging.Level.SEVERE, nlblhistoricoch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HistóricoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HistóricoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HistóricoFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel UltimosArtis;
    private javax.swing.JButton btnCarregarHistorico;
    private javax.swing.JLabel lblHistorico;
    // End of variables declaration                   
}
