package view;

/**
 *
 * @author unicmcruz
 */
public class InicioFrame extends javax.swing.JFrame {

    /**
     * Creates new form InicioFrame
     */
    public InicioFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bt_curtidas_inicio1 = new javax.swing.JButton();
        bt_adicionar_inicio = new javax.swing.JButton();
        bt_excluirr_inicio = new javax.swing.JButton();
        bt_ouvir_inicio = new javax.swing.JButton();
        bt_buscar_inicio = new javax.swing.JButton();
        bt_curtidas_inicio = new javax.swing.JButton();
        bt_historico_inicio = new javax.swing.JButton();

        bt_curtidas_inicio1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_curtidas_inicio1.setText("Curtidas");
        bt_curtidas_inicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtidas_inicio1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_adicionar_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_adicionar_inicio.setText("Adicionar");
        bt_adicionar_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionar_inicioActionPerformed(evt);
            }
        });

        bt_excluirr_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_excluirr_inicio.setText("Excluir");
        bt_excluirr_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirr_inicioActionPerformed(evt);
            }
        });

        bt_ouvir_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_ouvir_inicio.setText("Ouvir");
        bt_ouvir_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ouvir_inicioActionPerformed(evt);
            }
        });

        bt_buscar_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_buscar_inicio.setText("Buscar");
        bt_buscar_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscar_inicioActionPerformed(evt);
            }
        });

        bt_curtidas_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_curtidas_inicio.setText("Curtidas");
        bt_curtidas_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtidas_inicioActionPerformed(evt);
            }
        });

        bt_historico_inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_historico_inicio.setText("Histórico");
        bt_historico_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historico_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_adicionar_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_excluirr_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_ouvir_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_buscar_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_curtidas_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_historico_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bt_adicionar_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_excluirr_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_ouvir_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_buscar_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_historico_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_curtidas_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bt_adicionar_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        PlaylistFrame pf= new PlaylistFrame();
        pf.setVisible(true);
    }                                                   

    private void bt_excluirr_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        ExcluirFrame pf= new ExcluirFrame();
        pf.setVisible(true);
    }                                                  

    private void bt_buscar_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        PesquisaFrame pf= new PesquisaFrame();
        pf.setVisible(true);
    }                                                

    private void bt_ouvir_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                
        OuvirFrame pf= new OuvirFrame();
        pf.setVisible(true);
    }                                               

    private void bt_curtidas_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        CurtidasFrame pf= new CurtidasFrame();
        pf.setVisible(true);
    }                                                  

    private void bt_historico_inicioActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        HistoricoFrame pf= new HistoricoFrame();
        pf.setVisible(true);
    }                                                   

    private void bt_curtidas_inicio1ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InicioFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_adicionar_inicio;
    private javax.swing.JButton bt_buscar_inicio;
    private javax.swing.JButton bt_curtidas_inicio;
    private javax.swing.JButton bt_curtidas_inicio1;
    private javax.swing.JButton bt_excluirr_inicio;
    private javax.swing.JButton bt_historico_inicio;
    private javax.swing.JButton bt_ouvir_inicio;
    // End of variables declaration                   
}
