package view;

import controller.ControllerOuvir;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author mcruz
 */
public class OuvirFrame extends javax.swing.JFrame {
    private ControllerOuvir c;
    
    public OuvirFrame() {
        initComponents();
        c = new ControllerOuvir(this);
        c.carregarArtistasOuvir();
        c.carregarPlaylistOuvir();
    }

    public OuvirFrame(JButton bt_excluir_playlist, JLabel ouvir_playlist, JTextField txt_excluir_playlist) {
       
        this.ouvir_playlist = ouvir_playlist;
        
    }

    public JLabel getOuvir_playlist() {
        return ouvir_playlist;
    }

    public void setOuvir_playlist(JLabel ouvir_playlist) {
        this.ouvir_playlist = ouvir_playlist;
    }
 
    
    public OuvirFrame(JButton bt_excluir_artista, JTextField txt_excluir_artista) {
        this.bt_excluir_artista = bt_excluir_artista;
        this.txt_excluir_artista = txt_excluir_artista;
    }

    public JButton getBt_excluir_artista() {
        return bt_excluir_artista;
    }

    public void setBt_excluir_artista(JButton bt_excluir_artista) {
        this.bt_excluir_artista = bt_excluir_artista;
    }

    public JTextField getTxt_excluir_artista() {
        return txt_excluir_artista;
    }

    public void setTxt_excluir_artista(JTextField txt_excluir_artista) {
        this.txt_excluir_artista = txt_excluir_artista;
    }
    

    public OuvirFrame(JLabel ouvir_artista) {
        this.ouvir_artista = ouvir_artista;
    }

    public JLabel getOuvir_artista() {
        return ouvir_artista;
    }

    public void setOuvir_artista(JLabel ouvir_artista) {
        this.ouvir_artista = ouvir_artista;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ouvir_artista = new javax.swing.JLabel();
        artis = new javax.swing.JLabel();
        txt_excluir_artista = new javax.swing.JTextField();
        bt_excluir_artista = new javax.swing.JButton();
        playlistst = new javax.swing.JLabel();
        ouvir_playlist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ouvir_artista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ouvir_artista.setText("''");

        artis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        artis.setText("Artistas");

        txt_excluir_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_excluir_artistaActionPerformed(evt);
            }
        });

        bt_excluir_artista.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        bt_excluir_artista.setText("Excluir");
        bt_excluir_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_artistaActionPerformed(evt);
            }
        });

        playlistst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        playlistst.setText("Playlist");

        ouvir_playlist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ouvir_playlist.setText("''");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(artis, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(playlistst, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(bt_excluir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ouvir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(ouvir_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_excluir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artis)
                    .addComponent(playlistst, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ouvir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ouvir_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(txt_excluir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_excluir_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txt_excluir_artistaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void bt_excluir_artistaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        c.remover_artista();
    }                                                  

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OuvirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OuvirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OuvirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OuvirFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OuvirFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel artis;
    private javax.swing.JButton bt_excluir_artista;
    private javax.swing.JLabel ouvir_artista;
    private javax.swing.JLabel ouvir_playlist;
    private javax.swing.JLabel playlistst;
    private javax.swing.JTextField txt_excluir_artista;
    // End of variables declaration                   


}
