package view;

import controller.ControllerPesquisa;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;



/**
 *
 * @author mcruz
 */
public class PesquisaFrame extends javax.swing.JFrame {

    private ControllerPesquisa c;
    
    public PesquisaFrame() {
        initComponents();
        c = new ControllerPesquisa(this);
    }
    
    
    public PesquisaFrame(JButton bt_adicionar_pesquisa, JButton bt_buscar_pesquisa, JLabel lbl_senha_altexc, JTextField txt_buscar_pesquisa) {
        this.bt_adicionar_pesquisa = bt_adicionar_pesquisa;
        this.bt_buscar_pesquisa = bt_buscar_pesquisa;
        this.lbl_senha_altexc = lbl_senha_altexc;
        this.txt_buscar_pesquisa = txt_buscar_pesquisa;
        this.bt_curtir = bt_curtir ;
    }

    public JButton getBt_curtir() {
        return bt_curtir;
    }

    public void setBt_curtir(JButton bt_curtir) {
        this.bt_curtir = bt_curtir;
    }

    
    public JLabel getLbl_resultado_pesquisa() {
    return lbl_resultado_pesquisa;
    }

    public void setLbl_resultado_pesquisa(JLabel lbl_resultado_pesquisa) {
    this.lbl_resultado_pesquisa = lbl_resultado_pesquisa;
    }

    
    public JButton getBt_adicionar_pesquisa() {
        return bt_adicionar_pesquisa;
    }

    public void setBt_adicionar_pesquisa(JButton bt_adicionar_pesquisa) {
        this.bt_adicionar_pesquisa = bt_adicionar_pesquisa;
    }

    public JButton getBt_buscar_pesquisa() {
        return bt_buscar_pesquisa;
    }

    public void setBt_buscar_pesquisa(JButton bt_buscar_pesquisa) {
        this.bt_buscar_pesquisa = bt_buscar_pesquisa;
    }

    public JLabel getLbl_senha_altexc() {
        return lbl_senha_altexc;
    }

    public void setLbl_senha_altexc(JLabel lbl_senha_altexc) {
        this.lbl_senha_altexc = lbl_senha_altexc;
    }

    public JTextField getTxt_buscar_pesquisa() {
        return txt_buscar_pesquisa;
    }

    public void setTxt_buscar_pesquisa(JTextField txt_buscar_pesquisa) {
        this.txt_buscar_pesquisa = txt_buscar_pesquisa;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbl_senha_altexc = new javax.swing.JLabel();
        txt_buscar_pesquisa = new javax.swing.JTextField();
        bt_buscar_pesquisa = new javax.swing.JButton();
        bt_adicionar_pesquisa = new javax.swing.JButton();
        lbl_resultado_pesquisa = new javax.swing.JLabel();
        bt_curtir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_senha_altexc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_senha_altexc.setText("Pesquisa:");

        bt_buscar_pesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_buscar_pesquisa.setText("Buscar");
        bt_buscar_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscar_pesquisaActionPerformed(evt);
            }
        });

        bt_adicionar_pesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_adicionar_pesquisa.setText("Adicionar");
        bt_adicionar_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_adicionar_pesquisaActionPerformed(evt);
            }
        });

        lbl_resultado_pesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        bt_curtir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_curtir.setText("Curtir");
        bt_curtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resultado_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscar_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_adicionar_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_senha_altexc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha_altexc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_buscar_pesquisa)
                .addGap(43, 43, 43)
                .addComponent(lbl_resultado_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(bt_adicionar_pesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_curtir)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        

    private void bt_buscar_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
     c.buscarPesquisa();
    }                                                  

    private void bt_adicionar_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
     c.adicionarPesquisa();
    }                                                     

    private void bt_curtirActionPerformed(java.awt.event.ActionEvent evt) {                                          
     c.adicionarCurtir();
    }                                         

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PesquisaFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_adicionar_pesquisa;
    private javax.swing.JButton bt_buscar_pesquisa;
    private javax.swing.JButton bt_curtir;
    private javax.swing.JLabel lbl_resultado_pesquisa;
    private javax.swing.JLabel lbl_senha_altexc;
    private javax.swing.JTextField txt_buscar_pesquisa;
    // End of variables declaration                   
}
