package view;

import controller.ControllerPlaylist;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author mcruz
 */
public class PlaylistFrame extends javax.swing.JFrame {

    /**
     * Creates new form Playlist
     */
    public PlaylistFrame() {
        initComponents();
        c=new ControllerPlaylist(this);
    }

    public JButton getAdicionar_play() {
        return adicionar_play;
    }

    public void setAdicionar_play(JButton adicionar_play) {
        this.adicionar_play = adicionar_play;
    }

    public JLabel getLbl_musica1() {
        return lbl_musica1;
    }

    public void setLbl_musica1(JLabel lbl_musica1) {
        this.lbl_musica1 = lbl_musica1;
    }

    public JLabel getLbl_musica2() {
        return lbl_musica2;
    }

    public void setLbl_musica2(JLabel lbl_musica2) {
        this.lbl_musica2 = lbl_musica2;
    }

    public JLabel getLbl_musica3() {
        return lbl_musica3;
    }

    public void setLbl_musica3(JLabel lbl_musica3) {
        this.lbl_musica3 = lbl_musica3;
    }

    public JLabel getLbl_musica4() {
        return lbl_musica4;
    }

    public void setLbl_musica4(JLabel lbl_musica4) {
        this.lbl_musica4 = lbl_musica4;
    }

    public JLabel getLbl_musica5() {
        return lbl_musica5;
    }

    public void setLbl_musica5(JLabel lbl_musica5) {
        this.lbl_musica5 = lbl_musica5;
    }

    public JLabel getLbl_nome_cadastro3() {
        return lbl_nome_cadastro3;
    }

    public void setLbl_nome_cadastro3(JLabel lbl_nome_cadastro3) {
        this.lbl_nome_cadastro3 = lbl_nome_cadastro3;
    }

    public JLabel getLbl_play() {
        return lbl_play;
    }

    public void setLbl_play(JLabel lbl_play) {
        this.lbl_play = lbl_play;
    }

    public JTextField getMusica1_play() {
        return musica1_play;
    }

    public void setMusica1_play(JTextField musica1_play) {
        this.musica1_play = musica1_play;
    }

    public JTextField getMusica2_play() {
        return musica2_play;
    }

    public void setMusica2_play(JTextField musica2_play) {
        this.musica2_play = musica2_play;
    }

    public JTextField getMusica3_play() {
        return musica3_play;
    }

    public void setMusica3_play(JTextField musica3_play) {
        this.musica3_play = musica3_play;
    }

    public JTextField getMusica4_play() {
        return musica4_play;
    }

    public void setMusica4_play(JTextField musica4_play) {
        this.musica4_play = musica4_play;
    }

    public JTextField getMusica5_play() {
        return musica5_play;
    }

    public void setMusica5_play(JTextField musica5_play) {
        this.musica5_play = musica5_play;
    }

    public JTextField getPlaylist_musica() {
        return playlist_musica;
    }

    public void setPlaylist_musica(JTextField playlist_musica) {
        this.playlist_musica = playlist_musica;
    }

    public JTextField getTxt_nome_cadastro() {
        return txt_nome_cadastro;
    }

    public void setTxt_nome_cadastro(JTextField txt_nome_cadastro) {
        this.txt_nome_cadastro = txt_nome_cadastro;
    }

    public JTextField getTxt_nome_cadastro3() {
        return txt_nome_cadastro3;
    }

    public void setTxt_nome_cadastro3(JTextField txt_nome_cadastro3) {
        this.txt_nome_cadastro3 = txt_nome_cadastro3;
    }

    public JTextField getTxt_nome_cadastro8() {
        return txt_nome_cadastro8;
    }

    public void setTxt_nome_cadastro8(JTextField txt_nome_cadastro8) {
        this.txt_nome_cadastro8 = txt_nome_cadastro8;
    }

    public JTextField getTxt_usuario_play() {
        return txt_usuario_play;
    }

    public void setTxt_usuario_play(JTextField txt_usuario_play) {
        this.txt_usuario_play = txt_usuario_play;
    }

    public JLabel getUsuario_play() {
        return usuario_play;
    }

    public void setUsuario_play(JLabel usuario_play) {
        this.usuario_play = usuario_play;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txt_nome_cadastro = new javax.swing.JTextField();
        txt_nome_cadastro3 = new javax.swing.JTextField();
        lbl_nome_cadastro3 = new javax.swing.JLabel();
        txt_nome_cadastro8 = new javax.swing.JTextField();
        lbl_musica1 = new javax.swing.JLabel();
        playlist_musica = new javax.swing.JTextField();
        adicionar_play = new javax.swing.JButton();
        musica1_play = new javax.swing.JTextField();
        musica2_play = new javax.swing.JTextField();
        lbl_play = new javax.swing.JLabel();
        lbl_musica2 = new javax.swing.JLabel();
        lbl_musica3 = new javax.swing.JLabel();
        lbl_musica4 = new javax.swing.JLabel();
        lbl_musica5 = new javax.swing.JLabel();
        musica3_play = new javax.swing.JTextField();
        musica4_play = new javax.swing.JTextField();
        musica5_play = new javax.swing.JTextField();
        usuario_play = new javax.swing.JLabel();
        txt_usuario_play = new javax.swing.JTextField();

        lbl_nome_cadastro3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nome_cadastro3.setText("Música2: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_musica1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica1.setText("Música1: ");

        playlist_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlist_musicaActionPerformed(evt);
            }
        });

        adicionar_play.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adicionar_play.setText("Adicionar");
        adicionar_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_playActionPerformed(evt);
            }
        });

        lbl_play.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_play.setText("Playlist: ");

        lbl_musica2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica2.setText("Música2: ");

        lbl_musica3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica3.setText("Música3: ");

        lbl_musica4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica4.setText("Música4: ");

        lbl_musica5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica5.setText("Música5: ");

        usuario_play.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario_play.setText("Usuario: ");

        txt_usuario_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario_playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_musica5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_musica4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_musica3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_musica1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_musica2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuario_play, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_play, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionar_play)
                    .addComponent(musica2_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica1_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playlist_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica3_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica4_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica5_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario_play, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playlist_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musica1_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_musica1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musica2_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_musica2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_musica3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica3_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_musica4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica4_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_musica5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musica5_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario_play, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(adicionar_play)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void adicionar_playActionPerformed(java.awt.event.ActionEvent evt) {                                               
        c.adicionarPlay();
    }                                              

    private void txt_usuario_playActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       
    }                                                

    private void playlist_musicaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Playlist().setVisible(true);
//            }
//        });
//    }

    private ControllerPlaylist c;
    // Variables declaration - do not modify                     
    private javax.swing.JButton adicionar_play;
    private javax.swing.JLabel lbl_musica1;
    private javax.swing.JLabel lbl_musica2;
    private javax.swing.JLabel lbl_musica3;
    private javax.swing.JLabel lbl_musica4;
    private javax.swing.JLabel lbl_musica5;
    private javax.swing.JLabel lbl_nome_cadastro3;
    private javax.swing.JLabel lbl_play;
    private javax.swing.JTextField musica1_play;
    private javax.swing.JTextField musica2_play;
    private javax.swing.JTextField musica3_play;
    private javax.swing.JTextField musica4_play;
    private javax.swing.JTextField musica5_play;
    private javax.swing.JTextField playlist_musica;
    private javax.swing.JTextField txt_nome_cadastro;
    private javax.swing.JTextField txt_nome_cadastro3;
    private javax.swing.JTextField txt_nome_cadastro8;
    private javax.swing.JTextField txt_usuario_play;
    private javax.swing.JLabel usuario_play;
    // End of variables declaration                   
}
